# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0004_auto_20170927_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
