# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_destinations', to='Belt.User')),
            ],
        ),
    ]
