# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0002_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destinations',
            new_name='user_destinations',
        ),
    ]
