# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0005_auto_20170927_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
